### ISSUE TITLE
Lesson Checklist for development and publication.

### ISSUE THREAD

**Issue by kekoziar** [LibraryCarpentry/lc-data-intro-archives#7]
Here is the checklist The Carpentries use to confirm lessons are ready to publish.  We can use it as a guide as we develop the lesson, and a final checklist when we think it's ready to publish.

- [ ] Example code chunks run as expected
- [ ] Challenges / exercises run as expected
- [ ] Challenge / exercise solutions are correct
- [ ] Call out boxes (exercises, discussions, tips, etc) render correctly
- [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)
- [ ] Each episode includes learning objectives
- [ ] Each episode includes questions
- [ ] Each episode includes key points
- [ ] Setup instructions are up-to-date, correct, clear, and complete
- [ ] File structure is clean (e.g. delete deprecated files, insure filenames are consistent)
- [ ] Some Instructor notes are provided
- [ ] Lesson links work as expected

**Comment by scottcpeterson** [comment]
Hi Kat,



Thanks for this. Could you also send me the two links you posted into the
Zoom chat today about being a maintainer? Sorry, I had them in Chrome, but
then it crashed and the links didn’t repopulate.



Best,



Scott



*From:* K.E. Koziar [mailto:notifications@github.com]
*Sent:* Friday, May 24, 2019 10:35 AM
*To:* LibraryCarpentry/lc-data-intro-archives
*Cc:* Subscribed
*Subject:* [LibraryCarpentry/lc-data-intro-archives] Lesson Checklist for
development and publication. (#7)



Here is the checklist The Carpentries use to confirm lessons are ready to
publish. We can use it as a guide as we develop the lesson, and a final
checklist when we think it's ready to publish.

   - [ ] Example code chunks run as expected
   - [ ] Challenges / exercises run as expected
   - [ ] Challenge / exercise solutions are correct
   - [ ] Call out boxes (exercises, discussions, tips, etc) render correctly
   - [ ] A schedule appears on the lesson homepage (e.g. not “00:00”)
   - [ ] Each episode includes learning objectives
   - [ ] Each episode includes questions
   - [ ] Each episode includes key points
   - [ ] Setup instructions are up-to-date, correct, clear, and complete
   - [ ] File structure is clean (e.g. delete deprecated files, insure
   filenames are consistent)
   - [ ] Some Instructor notes are provided
   - [ ] Lesson links work as expected

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/LibraryCarpentry/lc-data-intro-archives/issues/7?email_source=notifications&email_token=AD4OGGIVSQIU2A3CIN6EBSTPXARN3A5CNFSM4HPRNKCKYY3PNVWWK3TUL52HS4DFUVEXG43VMWVGG33NNVSW45C7NFSM4GVYGYFA>,
or mute the thread

**Comment by doingarchives** [comment]
@kekoziar Some open threads here ... might need some input from the emergent CAC.
